version: 2.1

commands:
  build:
    description: "template for all docker-* build jobs"
    parameters:
      tag:
        description: "image tag (full variant name) to be built"
        type:
          string
      deptag:
        description: "image tag (full variant name) this depends on (should _not_ be rebuilt)"
        type:
          string
        default: "core"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: make docker-<< parameters.tag >> -o docker-<< parameters.deptag >> GIT_DEPTH=--single-branch
          no_output_timeout: 30m
      - run:
          name: test image
          command: |
            mkdir test-results
            docker run --rm -v $PWD:/data ocrd/all:<< parameters.tag >> make -C /build/core deps-test test PYTEST_ARGS=--junitxml=/data/test-results/core.xml
      - store_test_results:
          path: test-results/core.xml
  deploy:
    description: "template for all docker-* deploy jobs"
    parameters:
      tag:
        description: "image tag (full variant name) to be pushed"
        type:
          string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Alias Docker image
          command: docker tag ocrd/all:<< parameters.tag >> ocrd/all:<< parameters.tag >>-git
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push images to Docker Hub
          no_output_timeout: 2.5h
          command: |
            docker push ocrd/all:<< parameters.tag >>
            docker push ocrd/all:<< parameters.tag >>-git
      - when:
          condition:
            equal: [ maximum, << parameters.tag >> ]
          steps:
            - run:
                name: store ocrd-all-tool.json
                command: |
                  id=`docker create ocrd/all:maximum`
                  docker cp $id:/build/ocrd-all-tool.json .
            - store_artifacts:
                path: ocrd-all-tool.json
                destination: ocrd-all-tool.json
            - run:
                name: store ocrd-all-module-dir.json
                command: |
                  id=`docker create ocrd/all:maximum`
                  docker cp $id:/build/ocrd-all-module-dir.json .
            - store_artifacts:
                path: ocrd-all-module-dir.json
                destination: ocrd-all-module-dir.json
      - when:
          condition:
            equal: [ maximum-cuda, << parameters.tag >> ]
          steps:
            - run:
                name: Create a date-versioned mirror of ocrd/all:maximum-cuda
                command: bash release.sh release-dockerhub
            - run:
                name: Update badge
                command: curl -X POST "$MICROBADGER_WEBHOOK" || true
      - when:
          # takes too long for 1h1m CircleCI timeout overall
          # also, storage is limited...
          condition: false
          steps:
            - run:
                name: persist image
                command: |
                  sudo apt install pigz
                  docker image save ocrd/all:<< parameters.tag >> | pigz --fast > ocrd-all-maximum.tar.gz
                no_output_timeout: 30m
            # can be downloaded from CircleCI.com and imported via "docker image load"
            - store_artifacts:
                path: ocrd-all-maximum.tar.gz
                destination: artifacts
    
jobs:
  build-mini:
    docker:
      - image: cimg/base:current-22.04
    parameters:
      variant:
        type:
          string
    steps:
      - build:
          tag: minim<< parameters.variant >>
  build-medi:
    docker:
      - image: cimg/base:current-22.04
    parameters:
      variant:
        type:
          string
    steps:
      - build:
          deptag: minim<< parameters.variant >>
          tag: medi<< parameters.variant >>
  build-maxi:
    docker:
      - image: cimg/base:current-22.04
    parameters:
      variant:
        type:
          string
    steps:
      - build:
          deptag: medi<< parameters.variant >>
          tag: maxim<< parameters.variant >>
  deploy-mini:
    docker:
      - image: cimg/base:current-22.04
    parameters:
      variant:
        type:
          string
    steps:
      - build:
          tag: minim<< parameters.variant >>
  deploy-medi:
    docker:
      - image: cimg/base:current-22.04
    parameters:
      variant:
        type:
          string
    steps:
      - build:
          tag: medi<< parameters.variant >>
  deploy-maxi:
    docker:
      - image: cimg/base:current-22.04
    parameters:
      variant:
        type:
          string
    steps:
      - build:
          tag: maxim<< parameters.variant >>

workflows:
  version: 2
  build:
    jobs:
      - build-mini:
          name: build-minim<< matrix.variant >>
          matrix:
            parameters:
              variant: [um, um-cuda]
          post-steps:
            - run:
                name: save image
                command: |
                  mkdir -p images
                  docker image save -o images/minim<< matrix.variant >>.tar ocrd/all:minim<< matrix.variant >>
                no_output_timeout: 30m
            - persist_to_workspace:
                root: .
                paths:
                  - images
                no_output_timeout: 30m
      - build-medi:
          name: build-medi<< matrix.variant >>
          matrix:
            parameters:
              variant: [um, um-cuda]
          requires:
            - build-minim<< matrix.variant >>
          pre-steps:
            - attach_workspace:
                at: .
            - run:
                name: load previous image
                command: docker image load < images/minim<< matrix.variant >>.tar
          post-steps:
            - run:
                name: save image
                command: |
                  mkdir -p images
                  docker image save -o images/medi<< matrix.variant >>.tar ocrd/all:medi<< matrix.variant >>
                no_output_timeout: 30m
            - persist_to_workspace:
                root: .
                paths:
                  - images
                no_output_timeout: 30m
      - build-maxi:
          name: build-maxim<< matrix.variant >>
          matrix:
            parameters:
              variant: [um, um-cuda]
          requires:
            - build-medi<< matrix.variant >>
          pre-steps:
            - attach_workspace:
                at: .
            - run:
                name: load previous image
                command: docker image load < images/medi<< matrix.variant >>.tar
          post-steps:
            - run:
                name: save image
                command: |
                  mkdir -p images
                  docker image save -o images/maxim<< matrix.variant >>.tar ocrd/all:maxim<< matrix.variant >>
                no_output_timeout: 30m
            - persist_to_workspace:
                root: .
                paths:
                  - images
                no_output_timeout: 30m
      - deploy-mini:
          name: deploy-minim<< matrix.variant >>
          matrix:
            parameters:
              variant: [um, um-cuda]
          requires:
            - build-minim<< matrix.variant >>
          pre-steps:
            - attach_workspace:
                at: .
            - run:
                name: load previous image
                command: docker image load < images/minim<< matrix.variant >>.tar
          filters:
            branches:
              only: master
      - deploy-medi:
          name: deploy-medi<< matrix.variant >>
          matrix:
            parameters:
              variant: [um, um-cuda]
          requires:
            - build-medi<< matrix.variant >>
          pre-steps:
            - attach_workspace:
                at: .
            - run:
                name: load previous image
                command: docker image load < images/medi<< matrix.variant >>.tar
          filters:
            branches:
              only: master
      - deploy-maxi:
          name: deploy-maxim<< matrix.variant >>
          matrix:
            parameters:
              variant: [um, um-cuda]
          requires:
            - build-maxim<< matrix.variant >>
          pre-steps:
            - attach_workspace:
                at: .
            - run:
                name: load previous image
                command: docker image load < images/maxim<< matrix.variant >>.tar
          filters:
            branches:
              only: master
  
